### ISSUE TITLE
Server disconnected (code: 1006)

### ISSUE THREAD

**Issue by nodecentral** [jlesage/docker-avidemux#1]
Hi

I’ve installed the Avidemux Docker on my qnap NAS (under host), but when I try to access it via the ip/port I reach a page that has a Red Cross saying "Server disconnected (code: 1006)" any ideas on what to do ?

**Comment by jlesage** [comment]
This is usually fixed by clearing your browser's cache.

**Comment by jlesage** [comment]
Closing the issue, please re-open if needed.
