### ISSUE TITLE
Avidemux docker on qnap jobs problem

### ISSUE THREAD

**Issue by lukjod** [jlesage/docker-avidemux#10]
Can't find a way to run jobs after adding it to que. I can see them on /share/CACHEDEV1_DATA/Download/config/avidemux/.avidemux6/jobs but how to run them?
I tried to use docker exec avidemux env HOME=/config s6-setuidgid app /usr/bin/avidemux3_jobs_qt5 but get such output:
env: can't execute 's6-setuidgid': No such file or directory

**Comment by jlesage** [comment]
Are you using the UI ?

**Comment by lukjod** [comment]
Yes, ui

**Comment by jlesage** [comment]
For now, you can login to the container using `docker exec -ti <container name> sh`.  Then, execute:
```
su-exec app env HOME=/config avidemux3_jobs_qt5
```

**Comment by lukjod** [comment]
Thank You, work great
