### ISSUE TITLE
Avidemux jobs

### ISSUE THREAD

**Issue by fatnasa** [jlesage/docker-avidemux#2]
Hello,

I’ve installed the Avidemux Docker on my qnap , everything seems to be fine for a single file encoding.
I'm not able to perform any avidemux jobs , i have created the jobs but i am not sure how exactly to start them..

do you have any ideas ?

thanks in advance

**Comment by jlesage** [comment]
Here there is a small howto: https://avidemux.org/smif/index.php?topic=16783.0

Since the there is another UI to run the jobs, you need to manually start it via the following command:
```
docker exec <container name> env HOME=/config s6-setuidgid app /usr/bin/avidemux3_jobs_qt5
```

**Comment by fatnasa** [comment]
thanks alot for this
