### ISSUE TITLE
Container appears to use CPU when idle.

### ISSUE THREAD

**Issue by CTJohnK** [jlesage/docker-avidemux#6]
I have a few other Docker Containers loaded and started.  The Avidemux container is the only one which shows CPU usage when the container is not being accessed.

Just thought I would let you know, it only shows about 6.1% so it's not bringing the system it its knees and I will only use it periodically so when not in use, it will be stopped.

Thank you for your earlier help.

**Comment by jlesage** [comment]
How do you get CPU usage ?  Do you see the same thing with `docker stats <container name>`?  What about `docker top <container name> -u` ?

**Comment by CTJohnK** [comment]
I’m viewing the CPU usage within the Docker program within Synology DSM 6.5.  I’m currently converting some videos, so once that is done I’ll run the two commands and yes, I’ll remember to run them from SSH not from Synology’s Container’s Terminal.  😊

 

Is there something specific I should look for in the output of those commands?

 

 

Sincerely,

John Knauer

**Comment by jlesage** [comment]
The first command shows the CPU usage of the container.

The second command shows info about processes running inside the container, include CPU usage for each of them.  This will indicate which one exactly is taking the CPU.  You can share this output.

**Comment by CTJohnK** [comment]
![image](https://user-images.githubusercontent.com/69587153/103652299-e68da880-4f30-11eb-99db-3d8774576e96.png)

![image](https://user-images.githubusercontent.com/69587153/103652488-31a7bb80-4f31-11eb-90b6-313d63b60564.png)

**Comment by jlesage** [comment]
Are you using the latest version of the Docker image ?

**Comment by CTJohnK** [comment]
When I requested the container, it was requested as ‘Latest’, so I presume so.  I’m not sure how to check to confirm it’s 1.3.0.

**Comment by jlesage** [comment]
You can get the version by running:
```
docker inspect -f '{{ index .Config.Labels "org.label-schema.version"}}' <container name>
```

**Comment by CTJohnK** [comment]
When I ran your command, it returned ‘unknown’, so I dumped the entire listing.  I see why it returned ‘unknown’.

When I installed the container, I used Synology’s ‘Registry’ to search for “avidemux”.  I then selected your version and clicked ‘Download’.  This prompted me to select a Tag, with “latest” being the default and what I selected.  It would appear something may not have worked correctly in this case.  I presume the information below is indicating I’m using 1.0, correct?

 

                "org.label-schema.description": "Docker container for Avidemux",

               "org.label-schema.name": "avidemux",

                "org.label-schema.schema-version": "1.0",

                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-avidemux",

                "org.label-schema.version": "unknown"

**Comment by jlesage** [comment]
`"org.label-schema.version": "unknown"` is really the field that should contains the version.  However, it seem that something went wrong when the last image was pushed: I also have `unknown` as the version...

Anyway, you should have this in the complete `docker inspect` output:
```
"Image": "sha256:f0684403e65a936459152976f16af4d8b421b51b5e71dece3689e11c42f9eb14"
```

**Comment by CTJohnK** [comment]
I do and the value matches.

I was thinking about this and in hindsight, it would make sense the VNC display would be ‘running’ in the background waiting for a connection request.  Does that sound reasonable?

**Comment by jlesage** [comment]
According to your `docker top` command, it's avidemux itself who is using some CPU.  I don't see this behaviour on my side.
Maybe you can share the full output of `docker inspect`?
Do you see the same thing after restarting the container ?

**Comment by CTJohnK** [comment]
Here you go, see below from the original query.  This morning I started the container, converted a small video file, then closed the project and the browser window.  The container (in Synology Docker) shows CPU usage 30-minutes or so after exiting the UI.  Could this be something related to how Synology has deployed Docker?  What platform are you running Docker?

 

admin@MediaServer5:~$ sudo docker inspect  avidemux

[

    {

        "Id": "baf5c442adc395725f2f11faa6a25462e1d91fbba58dde82798cee2ad5424e58",

        "Created": "2021-01-02T16:59:08.265879457Z",

        "Path": "/init",

        "Args": [],

        "State": {

            "Status": "running",

            "Running": true,

            "Paused": false,

            "Restarting": false,

            "OOMKilled": false,

            "Dead": false,

            "Pid": 472,

            "ExitCode": 0,

            "Error": "",

            "StartedAt": "2021-01-07T17:29:47.673738305Z",

            "FinishedAt": "2021-01-05T20:39:47.26339663Z",

            "StartedTs": 1610040587,

            "FinishedTs": 1609879187

        },

        "Image": "sha256:f0684403e65a936459152976f16af4d8b421b51b5e71dece3689e11c42f9eb14"

        "ResolvConfPath": "/volume1/@docker/containers/baf5c442adc395725f2f11faa6a25462e1d91fbba58dde82798cee2ad                              5424e58/resolv.conf <mailto:/volume1/@docker/containers/baf5c442adc395725f2f11faa6a25462e1d91fbba58dde82798cee2ad%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%205424e58/resolv.conf> ",

        "HostnamePath": "/volume1/@docker/containers/baf5c442adc395725f2f11faa6a25462e1d91fbba58dde82798cee2ad54                              24e58/hostname",

        "HostsPath": "/volume1/@docker/containers/baf5c442adc395725f2f11faa6a25462e1d91fbba58dde82798cee2ad5424e                              58/hosts",

        "LogPath": "/volume1/@docker/containers/baf5c442adc395725f2f11faa6a25462e1d91fbba58dde82798cee2ad5424e58                              /log.db <mailto:/volume1/@docker/containers/baf5c442adc395725f2f11faa6a25462e1d91fbba58dde82798cee2ad5424e58%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20/log.db> ",

        "Name": "/avidemux",

        "RestartCount": 0,

        "Driver": "btrfs",

        "Platform": "linux",

        "MountLabel": "",

        "ProcessLabel": "",

        "AppArmorProfile": "docker-default",

        "ExecIDs": null,

        "HostConfig": {

            "Binds": [

                "/volume1/multimedia/recordings:/storage/recordings:rw"

            ],

            "ContainerIDFile": "",

            "LogConfig": {

                "Type": "db",

                "Config": {}

            },

            "NetworkMode": "bridge",

            "PortBindings": {

                "5800/tcp": [

                    {

                        "HostIp": "0.0.0.0",

                        "HostPort": "5800"

                    }

                ],

                "5900/tcp": [

                    {

                        "HostIp": "0.0.0.0",

                        "HostPort": "5900"

                    }

                ]

            },

            "RestartPolicy": {

                "Name": "no",

                "MaximumRetryCount": 0

            },

            "AutoRemove": false,

            "VolumeDriver": "",

            "VolumesFrom": null,

            "CapAdd": [],

            "CapDrop": [],

            "Dns": [],

            "DnsOptions": [],

            "DnsSearch": [],

            "ExtraHosts": null,

            "GroupAdd": null,

            "IpcMode": "shareable",

            "Cgroup": "",

            "Links": null,

            "OomScoreAdj": 0,

            "PidMode": "",

            "Privileged": false,

            "PublishAllPorts": false,

            "ReadonlyRootfs": false,

            "SecurityOpt": null,

            "UTSMode": "",

            "UsernsMode": "",

            "ShmSize": 67108864,

            "Runtime": "runc",

            "Env": [

                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",

                "LANG=en_US.UTF-8",

                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",

                "S6_SERVICE_DEPS=1",

                "USER_ID=1035",

                "GROUP_ID=100",

                "APP_NAME=Avidemux",

                "APP_USER=app",

                "XDG_DATA_HOME=/config/xdg/data",

                "XDG_CONFIG_HOME=/config/xdg/config",

                "XDG_CACHE_HOME=/config/xdg/cache",

                "XDG_RUNTIME_DIR=/tmp/run/user/app",

                "DISPLAY=:0",

                "DISPLAY_WIDTH=1280",

                "DISPLAY_HEIGHT=768"

            ],

            "ConsoleSize": [

                0,

                0

            ],

            "Isolation": "",

            "CpuShares": 50,

            "Memory": 1073741824,

            "NanoCpus": 0,

            "CgroupParent": "",

            "BlkioWeight": 0,

            "BlkioWeightDevice": null,

            "BlkioDeviceReadBps": null,

            "BlkioDeviceWriteBps": null,

            "BlkioDeviceReadIOps": null,

            "BlkioDeviceWriteIOps": null,

            "CpuPeriod": 0,

            "CpuQuota": 0,

            "CpuRealtimePeriod": 0,

            "CpuRealtimeRuntime": 0,

            "CpusetCpus": "",

            "CpusetMems": "",

            "Devices": null,

            "DeviceCgroupRules": null,

            "DiskQuota": 0,

            "KernelMemory": 0,

            "MemoryReservation": 0,

            "MemorySwap": 2147483648,

            "MemorySwappiness": null,

            "OomKillDisable": false,

            "PidsLimit": 0,

            "Ulimits": null,

            "CpuCount": 0,

            "CpuPercent": 0,

            "IOMaximumIOps": 0,

            "IOMaximumBandwidth": 0,

            "MaskedPaths": [

                "/proc/asound",

                "/proc/acpi",

                "/proc/kcore",

                "/proc/keys",

                "/proc/latency_stats",

                "/proc/timer_list",

                "/proc/timer_stats",

                "/proc/sched_debug",

                "/proc/scsi",

                "/sys/firmware"

            ],

            "ReadonlyPaths": [

                "/proc/bus",

                "/proc/fs",

                "/proc/irq",

                "/proc/sys",

                "/proc/sysrq-trigger"

            ]

        },

        "GraphDriver": {

            "Data": null,

            "Name": "btrfs"

        },

        "Mounts": [

            {

                "Type": "volume",

                "Name": "4b7562995d1f0fd528869e301e49906c7b5bba3c029337d7c92a46d213ae1e58",

                "Source": "/volume1/@docker/volumes/4b7562995d1f0fd528869e301e49906c7b5bba3c029337d7c92a46d213ae                              1e58/_data",

                "Destination": "/config",

                "Driver": "local",

                "Mode": "",

                "RW": true,

                "Propagation": ""

            },

            {

                "Type": "volume",

                "Name": "a6c0fb9ed8c2b99ba615d89966981dbf8d44ed75810032496547c61d91f47fd7",

                "Source": "/volume1/@docker/volumes/a6c0fb9ed8c2b99ba615d89966981dbf8d44ed75810032496547c61d91f4                              7fd7/_data",

                "Destination": "/storage",

                "Driver": "local",

                "Mode": "",

                "RW": true,

                "Propagation": ""

            },

            {

                "Type": "bind",

                "Source": "/volume1/multimedia/recordings",

                "Destination": "/storage/recordings",

                "Mode": "rw",

                "RW": true,

                "Propagation": "rprivate"

            }

        ],

        "Config": {

            "Hostname": "avidemux",

            "Domainname": "",

            "User": "",

            "AttachStdin": false,

            "AttachStdout": false,

            "AttachStderr": false,

            "ExposedPorts": {

                "5800/tcp": {},

                "5900/tcp": {}

            },

            "Tty": true,

            "OpenStdin": true,

            "StdinOnce": false,

            "Env": [

                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",

                "LANG=en_US.UTF-8",

                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",

                "S6_SERVICE_DEPS=1",

                "USER_ID=1035",

                "GROUP_ID=100",

                "APP_NAME=Avidemux",

                "APP_USER=app",

                "XDG_DATA_HOME=/config/xdg/data",

                "XDG_CONFIG_HOME=/config/xdg/config",

                "XDG_CACHE_HOME=/config/xdg/cache",

                "XDG_RUNTIME_DIR=/tmp/run/user/app",

                "DISPLAY=:0",

                "DISPLAY_WIDTH=1280",

                "DISPLAY_HEIGHT=768"

            ],

            "Cmd": [

                "/init"

            ],

            "Image": "jlesage/avidemux:latest",

            "Volumes": {

                "/config": {},

                "/storage": {}

            },

            "WorkingDir": "/tmp",

            "Entrypoint": null,

            "OnBuild": null,

            "Labels": {

                "org.label-schema.description": "Docker container for Avidemux",

                "org.label-schema.name": "avidemux",

                "org.label-schema.schema-version": "1.0",

                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-avidemux",

                "org.label-schema.version": "unknown"

            },

            "DDSM": false

        },

        "NetworkSettings": {

            "Bridge": "",

            "SandboxID": "6c9ef4aef765a8ac3249929d3d65586512741fdd62a99dc58ed2bb0784b4248a",

            "HairpinMode": false,

            "LinkLocalIPv6Address": "",

            "LinkLocalIPv6PrefixLen": 0,

            "Ports": {

                "5800/tcp": [

                    {

                        "HostIp": "0.0.0.0",

                        "HostPort": "5800"

                    }

                ],

                "5900/tcp": [

                    {

                        "HostIp": "0.0.0.0",

                        "HostPort": "5900"

                    }

                ]

            },

            "SandboxKey": "/var/run/docker/netns/6c9ef4aef765",

            "SecondaryIPAddresses": null,

            "SecondaryIPv6Addresses": null,

            "EndpointID": "500460cd2dffbb63432d42269751f10ff3475a24e60092bbdd41af9f7bd63ace",

            "Gateway": "172.17.0.1",

            "GlobalIPv6Address": "",

            "GlobalIPv6PrefixLen": 0,

            "IPAddress": "172.17.0.3",

            "IPPrefixLen": 16,

            "IPv6Gateway": "",

            "MacAddress": "02:42:ac:11:00:03",

            "Networks": {

                "bridge": {

                    "IPAMConfig": null,

                    "Links": null,

                    "Aliases": null,

                    "NetworkID": "974a94b15bf3a8a7b969d29682a2ba6eb945cfbcada0d6b5e1127729dca7e7b5",

                    "EndpointID": "500460cd2dffbb63432d42269751f10ff3475a24e60092bbdd41af9f7bd63ace",

                    "Gateway": "172.17.0.1",

                    "IPAddress": "172.17.0.3",

                    "IPPrefixLen": 16,

                    "IPv6Gateway": "",

                    "GlobalIPv6Address": "",

                    "GlobalIPv6PrefixLen": 0,

                    "MacAddress": "02:42:ac:11:00:03",

                    "DriverOpts": null

                }

            }

        }

    }

]

**Comment by jlesage** [comment]
Note that closing the browser window doesn't stop the container.  If you really stop the container (the equivalent of running `docker stop avidemux`), you should not see any CPU usage from the container.

**Comment by CTJohnK** [comment]
I was expecting if Avidemux was started, a file was converted, completed and the browser closed, to see zero CPU usage 30 or more minutes later.  This is how the standalone version of Avidemux is behaving on a Windows PC based on  Windows Task Manager.

I'm closing this as I think the difference might be VNC using some CPU waiting for a connection perhaps.

**Comment by jlesage** [comment]
So you are saying that with the Windows version, you see 30min of CPU usage after the end of the conversion ?

And with the container, CPU usage never comes back to 0 after the conversion?

**Comment by CTJohnK** [comment]
Sorry no.  The Windows version shows zero CPU usage 30 minutes after the video conversion is complete (actually as soon as the conversion completes the CPU usage drops to zero).  The container version shows a small amount of CPU usage 30 minutes (and beyond) after the video conversion is complete.In short, the container version appears to be doing something when it should not be doing anything.Unless you disagree, I think it might be related to VNC.

**Comment by jlesage** [comment]
According to the information you provided, the problem doesn't seem related to the VNC connection, but with Avidemux itself.
If after a restart of the container (`docker restart <container name>`) you don't perform any conversion, do you see CPU activity from the container ?

**Comment by CTJohnK** [comment]
Sorry for the delay, I started the container yesterday and have not touched it, the Docker UI is showing zero CPU for the container.  As soon as I connect to it (no data loading, no file search, just connecting), it registers some CPU and continues to show a small amount of usage after that.

**Comment by CTJohnK** [comment]
Hello.

 

I just wanted to give you an update.  I’ve been keeping an eye on the container and interestingly – after about 5-days of idle time which showed a small amount of CPU usage, the container now shows zero CPU usage.

 

Also for your information, I’ve been using Avidemux to prune out commercials from recordings.  After six to eight files have been saved, I start getting errors upon saving indicating the save completed improperly and the file is now incomplete.  Shutting down the container and starting it up again and reprocessing the same file seems to address the issue.  This does appear to be an Avidemux issue, nothing to do with the container as I was able to replicate the same issue using the stand-alone version of Avidemux.

 

Thank you for your help.

 

Sincerely,

John Knauer
