### ISSUE TITLE
Mobile compatibility 

### ISSUE THREAD

**Issue by EWoodard** [jlesage/docker-avidemux#8]
Hello,

  Thanks for your work on this. 
 I installed it on a NAS to do server side editing. It works well. 
My idea is to be able to edit video anywhere remotely. Especially on my phone. 
However the front end doesn’t seem well suited for mobile. 
Mainly because the controls are hard to use and zooming is difficult.
Is it possible to create a mobile interface? I’d it’s too time consuming, could you point me in the right direction that I could try my self? 
One other thing is it possible to default the zoom to ‘0’ fit view?  Thanks again

**Comment by jlesage** [comment]
Sorry, I know this is an old issue.  I was talking about a native VNC client application on the phone that could be used to connect to the container directly.
